[package]
name = "sqlstate"
version = "0.0.0"
authors = ["Luc Street <lucis-fluxum@users.noreply.github.com>"]
description = "..."
repository = "https://github.com/lucis-fluxum/sqlstate-rs"
license = "MIT"
edition = "2018"

[dependencies]
sqlstate-macros = { path = "../sqlstate-macros", version = "0.0.0" }
thiserror = "1.0.0"
