pub enum Category {
    Success,
    Warning,
    NoData,
    Exception,
}

#[non_exhaustive]
pub enum Class {
    Success,
    Warning,
    NoData,
    DynamicSqlError,
    ConnectionException,
    TriggeredActionException,
    FeatureNotSupported,
    InvalidTargetTypeSpecification,
    InvalidSchemaNameListSpecification,
    LocatorException,
    ResignalWhenHandlerNotActive,
    InvalidGrantor,
    InvalidSqlInvokedProcedureReference,
    SqlXmlMappingError,
    InvalidRoleSpecification,
    InvalidTransformGroupNameSpecification,
    TargetTableDisagreesWithCursorSpecification,
    AttemptToAssignToNonUpdatableColumn,
    AttemptToAssignToOrderingColumn,
    ProhibitedStatementDuringTriggerExecution,
    InvalidForeignServerSpecification,
    PassthroughSpecificCondition,
    DiagnosticsException,
    XQueryError,
    CaseNotFoundForCaseStatement,
    CardinalityViolation,
    DataException,
    IntegrityConstraintViolation,
    InvalidCursorState,
    InvalidTransactionState,
    InvalidSqlStatementName,
    TriggeredDataChangeViolation,
    InvalidAuthorizationSpecification,
    DependentPrivilegeDescriptorsExist,
    InvalidCharsetName,
    InvalidTransactionTermination,
    InvalidConnectionName,
    SqlRoutineException,
    InvalidCollationName,
    InvalidSqlStatementIdentifier,
    InvalidSqlDescriptorName,
    InvalidCursorName,
    InvalidConditionNumber,
    CursorSensitivityException,
    ExternalRoutineException,
    ExternalRoutineInvocationException,
    SavepointException,
    AmbiguousCursorName,
    InvalidCatalogName,
    InvalidSchemaName,
    TransactionRollback,
    SyntaxErrorOrAccessRuleViolation,
    WithCheckOptionViolation,
    UnhandledUserDefinedException,
    OlbSpecificError,
    JavaDdl,
    DatalinkException,
    FdwSpecificCondition,
    CliSpecificCondition,
    RemoteDatabaseAccess,
}

#[non_exhaustive]
pub enum Subclass {
    // Warning
    CursorOperationConflict,
    DisconnectError,
    NullValueEliminatedInSetFunction,
    StringDataRightTruncation, // Also DataException
    InsufficientItemDescriptorAreas,
    PrivilegeNotRevoked,
    PrivilegeNotGranted,
    SearchConditionTooLongForInformationSchema,
    QueryExpressionTooLongForInformationSchema,
    DefaultValueTooLongForInformationSchema,
    ResultSetsReturned,
    AdditionalResultSetsReturned,
    AttemptToReturnTooManyResultSets,
    StatementTooLongForInformationSchema,
    ColumnCannotBeMapped,
    SqlJavaPathTooLongForInformationSchema,
    InvalidNumberOfConditions,
    ArrayDataRightTruncation, // Also DataException
    // NoData
    NoAdditionalResultSetsReturned,
    // DynamicSqlError
    UsingClauseDoesNotMatchDynamicParameterSpecifications,
    UsingClauseDoesNotMatchTargetSpecifications,
    CursorSpecificationCannotBeExecuted,
    UsingClauseRequiredForDynamicParameters,
    PreparedStatementNotACursorSpecification,
    RestrictedDataTypeAttributeViolation,
    UsingClauseRequiredForResultFields,
    InvalidDescriptorCount,
    InvalidDescriptorIndex,
    DataTypeTransformFunctionViolation,
    UndefinedDataValue,
    InvalidDataTarget,
    InvalidLevelValue,
    InvalidDatetimeIntervalCode,
    // ConnectionException
    SqlClientUnableToEstablishSqlConnection,
    ConnectionNameInUse,
    ConnectionDoesNotExist,
    SqlServerRejectedEstablishmentOfSqlConnection,
    ConnectionFailure,
    TransactionResolutionUnknown,
    // FeatureNotSupported
    MultipleServerTransactions,
    // LocatorException
    InvalidLocatorSpecification,
    // SqlXmlMappingError
    UnmappableXmlName,
    InvalidXmlCharacter,
    // ProhibitedStatementDuringTriggerExecution
    ModifyTableModifiedByDataChangeDeltaTable, // Also TriggeredDataChangeViolation
    // PassthroughSpecificCondition
    InvalidCursorOption,
    InvalidCursorAllocation,
    // DiagnosticsException
    MaximumNumberOfStackedDiagnosticsAreasExceeded,
    StackedDiagnosticsAccessedWithoutActiveHandler,
    // DataException
    NullValueNoIndicatorParameter,
    NumericValueOutOfRange,
    NullValueNotAllowed, // Also ExternalRoutineInvocationException
    ErrorInAssignment,
    InvalidIntervalFormat,
    InvalidDatetimeFormat,
    DatetimeFieldOverflow,
    InvalidTimeZoneDisplacementValue,
    EscapeCharacterConflict,
    InvalidUseOfEscapeCharacter,
    InvalidEscapeOctet,
    NullValueInArrayTarget,
    ZeroLengthCharacterString,
    MostSpecificTypeMismatch,
    SequenceGeneratorLimitExceeded,
    NonidenticalNotationsWithTheSameName,
    NonidenticalUnparsedEntitiesWithTheSameName,
    NotAnXmlDocument,
    InvalidXmlDocument,
    InvalidXmlContent,
    IntervalValueOutOfRange,
    MultisetValueOverflow,
    XmlValueOverflow,
    InvalidComment,
    InvalidProcessingInstruction,
    NotAnXQueryDocumentNode,
    InvalidXQueryContextItem,
    XQuerySerializationError,
    InvalidIndicatorParameterValue,
    SubstringError,
    DivisionByZero,
    InvalidPrecedingOrFollowingSizeInWindowFunction,
    InvalidArgumentForNtileFunction,
    IntervalFieldOverflow,
    InvalidArgumentForNthValueFunction,
    InvalidDataSpecifiedForDatalink,
    InvalidCharacterValueForCast,
    InvalidEscapeCharacter,
    NullArgumentPassedToDatalinkConstructor,
    InvalidRegularExpression,
    NullRowNotPermittedInTable,
    DatalinkValueExceedsMaximumLength,
    InvalidArgumentForNaturalLogarithm,
    InvalidArgumentForPowerFunction,
    InvalidArgumentForWidthBucketFunction,
    InvalidRowVersion,
    XQuerySequenceCannotBeValidated,
    XQueryDocumentNodeCannotBeValidated,
    NoXmlSchemaFound,
    ElementNamespaceNotDeclared,
    GlobalElementNotDeclared,
    NoXmlElementWithSpecifiedQName,
    NoXmlElementWithSpecifiedNamespace,
    ValidationFailure,
    InvalidQueryRegularExpression,
    InvalidQueryOptionFlag,
    AttemptToReplaceAZeroLengthString,
    InvalidQueryReplacementString,
    InvalidRowCountInFetchFirstClause,
    InvalidRowCountInResultOffsetClause,
    CharacterNotInRepertoire,
    IndicatorOverflow,
    InvalidParameterValue,
    UnterminatedCString,
    InvalidEscapeSequence,
    StringDataLengthMismatch,
    TrimError,
    NoncharacterInUcsString,
    NullValueInFieldReference,
    NullValueSubstitutedForMutatorSubjectParameter,
    ArrayElementError,
    InvalidRepeatArgumentInASampleClause,
    InvalidSampleSize,
    // IntegrityConstraintViolation
    RestrictViolation,
    // InvalidTransactionState
    ActiveSqlTransaction,
    BranchTransactionAlreadyActive,
    InappropriateAccessModeForBranchTransaction,
    InappropriateIsolationLevelForBranchTransaction,
    NoActiveSqlTransactionForBranchTransaction,
    ReadOnlySqlTransaction,
    SchemaAndDataStatementMixingNotSupported,
    HeldCursorRequiresSameIsolationLevel,
    // SqlRoutineException
    ModifyingSqlDataNotPermitted,    // Also ExternalRoutineException
    ProhibitedSqlStatementAttempted, // Also ExternalRoutineException
    ReadingSqlDataNotPermitted,      // Also ExternalRoutineException
    FunctionExecutedNoReturnStatement,
    // CursorSensitivityException
    RequestRejected,
    RequestFailed,
    // ExternalRoutineException
    ContainingSqlNotPermitted,
    // SavepointException
    InvalidSavepointSpecification,
    TooManySavepoints,
    // TransactionRollback
    SerializationFailure,
    IntegrityConstraintViolation,
    StatementCompletionUnknown,
    TriggeredActionException,
    // JavaDdl
    InvalidUrl,
    InvalidJarName,
    InvalidClassDeletion,
    InvalidReplacement,
    AttemptToReplaceUninstalledJar,
    AttemptToRemoveUninstalledJar,
    InvalidJarRemoval,
    InvalidPath,
    SelfReferencingPath,
    InvalidJarNameInPath,
    UnresolvedClassName,
    // OlbSpecificError
    UnsupportedFeature,
    InvalidClassDeclaration,
    InvalidOlbColumnName,
    InvalidNumberOfColumns,
    InvalidProfileState,
    // DatalinkException
    ExternalFileNotLinked,
    ExternalFileAlreadyLinked,
    ReferencedFileDoesNotExist,
    InvalidWriteToken,
    InvalidDatalinkConstruction,
    InvalidWritePermissionForUpdate,
    ReferencedFileNotValid,
    // FdwSpecificCondition
    MemoryAllocationError,
    DynamicParameterValueNeeded, // Also CliSpecificCondition
    InvalidDataType,             // Also CliSpecificCondition
    ColumnNameNotFound,
    InvalidDataTypeDescriptors,
    InvalidFdwColumnName,
    InvalidColumnNumber,
    InvalidUseOfNullPointer, // Also CliSpecificCondition
    InvalidStringFormat,
    InvalidHandle, // Also CliSpecificCondition
    InvalidOptionIndex,
    InvalidOptionName,
    OptionNameNotFound,
    ReplyHandle,
    UnableToCreateExecution,
    UnableToCreateReply,
    UnableToEstablishConnection,
    NoSchemas,
    SchemaNotFound,
    TableNotFound,
    FunctionSequenceError,             // Also CliSpecificCondition
    LimitOnNumberOfHandlesExceeded,    // Also CliSpecificCondition
    InconsistentDescriptorInformation, // Also CliSpecificCondition
    InvalidAttributeValue,             // Also CliSpecificCondition
    InvalidStringLengthOrBufferLength, // Also CliSpecificCondition
    InvalidDescriptorFieldIdentifier,  // Also CliSpecificCondition
    // CliSpecificCondition
    InvalidDataTypeInApplicationDescriptor,
    AssociatedStatementIsNotPrepared,
    OperationCanceled,
    AttributeCannotBeSetNow,
    InvalidTransactionOperationCode,
    MemoryManagementError,
    InvalidUseOfAutomaticallyAllocatedDescriptorHandle,
    ServerDeclinedCancellationRequest,
    NonStringDataCannotBeSentInPieces,
    AttemptToConcatenateANullValue,
    NonStringDataCannotBeUsedWithStringRoutine,
    InvalidAttributeIdentifier,
    InvalidDatalinkValue,
    InvalidFunctionIdSpecified,
    InvalidInformationType,
    ColumnTypeOutOfRange,
    ScopeOutOfRange,
    NullableTypeOutOfRange,
    InvalidRetrievalCode,
    InvalidLengthPrecisionValue,
    InvalidParamterMode,
    InvalidFetchOrientation,
    RowValueOutOfRange,
    InvalidCursorPosition,
    OptionalFeatureNotImplemented,
    // RemoteDatabaseAccess
    Iso9579,
}

pub struct SqlState {
    category: Category,
    class: Class,
    subclass: Option<Subclass>,
}
